### ISSUE TITLE
Doesn't work with Android Pie

### ISSUE THREAD

**Issue by and7ey** [shannah/DIYRemote#1]
useClearTextTraffic = "true" should be added, otherwise irdb.tk doesn't work

**Comment by shannah** [comment]
Thanks.  Looks like a problem with their certificate. Probably best for them to fix it than for me to work around it.  I'll see about reporting it to them.

**Comment by shannah** [comment]
I've filed an issue with there.  https://github.com/probonopd/irdb/issues/38

**Comment by and7ey** [comment]
Thanks. Your app supports user pages also. Believe it better to allow a user to choose HTTP or HTTPS. Now, your app supports HTTPS only.

**Comment by shannah** [comment]
I've pushed a new build that should fix this issue.
